//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GetPointEntities : DbContext
    {
        public GetPointEntities()
            : base("name=GetPointEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Area> tbl_Area { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
        public virtual DbSet<tbl_CustomerAddress> tbl_CustomerAddress { get; set; }
        public virtual DbSet<tbl_CustomerFav> tbl_CustomerFav { get; set; }
        public virtual DbSet<tbl_Groups> tbl_Groups { get; set; }
        public virtual DbSet<tbl_Item> tbl_Item { get; set; }
        public virtual DbSet<tbl_ItemColor> tbl_ItemColor { get; set; }
        public virtual DbSet<tbl_ItemGroup> tbl_ItemGroup { get; set; }
        public virtual DbSet<tbl_ItemImage> tbl_ItemImage { get; set; }
        public virtual DbSet<tbl_ItemSize> tbl_ItemSize { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_OrderItem> tbl_OrderItem { get; set; }
        public virtual DbSet<tbl_OrderStatus> tbl_OrderStatus { get; set; }
        public virtual DbSet<tbl_PaymentType> tbl_PaymentType { get; set; }
        public virtual DbSet<tbl_ShoppingCartItem> tbl_ShoppingCartItem { get; set; }
        public virtual DbSet<tbl_Slider> tbl_Slider { get; set; }
        public virtual DbSet<tbl_SubCategory> tbl_SubCategory { get; set; }
        public virtual DbSet<tbl_Supplier> tbl_Supplier { get; set; }
        public virtual DbSet<tbl_Systemconfig> tbl_Systemconfig { get; set; }
        public virtual DbSet<VW_City_Area> VW_City_Area { get; set; }
        public virtual DbSet<VW_GroupItem> VW_GroupItem { get; set; }
        public virtual DbSet<VW_ShoppingCart> VW_ShoppingCart { get; set; }
        public virtual DbSet<VW_Item> VW_Item { get; set; }
        public virtual DbSet<VW_OldOrders> VW_OldOrders { get; set; }
    }
}
