//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Supplier()
        {
            this.tbl_Item = new HashSet<tbl_Item>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierTitle { get; set; }
        public Nullable<bool> SupplierIsActive { get; set; }
        public string SupplierEmail { get; set; }
        public string SupplierMobile { get; set; }
        public string SupplierTele { get; set; }
        public string SupplierContactPerson { get; set; }
        public string SupplierContactMobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Item> tbl_Item { get; set; }
    }
}
