//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemGroup
    {
        public int ItemGroupId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual tbl_Groups tbl_Groups { get; set; }
        public virtual tbl_Item tbl_Item { get; set; }
    }
}
