//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubCategory
    {
        public int SubCategoryID { get; set; }
        public string SubCategoryTitleAr { get; set; }
        public string SubCategoryTitleEn { get; set; }
        public string SubCategoryPic { get; set; }
        public Nullable<bool> SubCategoryIsActive { get; set; }
        public Nullable<int> SubCategorySort { get; set; }
        public string SubCategoryDescription { get; set; }
        public int CategoryID { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
