//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Item()
        {
            this.tbl_ItemColor = new HashSet<tbl_ItemColor>();
            this.tbl_ItemGroup = new HashSet<tbl_ItemGroup>();
            this.tbl_ItemImage = new HashSet<tbl_ItemImage>();
            this.tbl_ItemSize = new HashSet<tbl_ItemSize>();
            this.tbl_OrderItem = new HashSet<tbl_OrderItem>();
            this.tbl_Slider = new HashSet<tbl_Slider>();
        }
    
        public int ItemID { get; set; }
        public int CategoryID { get; set; }
        public string ItemTitle { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public string ItemPic { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<double> Points { get; set; }
        public Nullable<double> PointsCredit { get; set; }
        public Nullable<int> NoOfViews { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_Supplier tbl_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemColor> tbl_ItemColor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemGroup> tbl_ItemGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemImage> tbl_ItemImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemSize> tbl_ItemSize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderItem> tbl_OrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Slider> tbl_Slider { get; set; }
    }
}
