//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerFav
    {
        public int CustomerFavID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
