//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Groups()
        {
            this.tbl_ItemGroup = new HashSet<tbl_ItemGroup>();
        }
    
        public int GroupId { get; set; }
        public string GroupTitleAr { get; set; }
        public string GroupTitleEn { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string GroupPic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemGroup> tbl_ItemGroup { get; set; }
    }
}
