//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_City_Area
    {
        public int CityID { get; set; }
        public string CityTitle { get; set; }
        public string AreaTitle { get; set; }
        public int AreaID { get; set; }
    }
}
