//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GroupItem
    {
        public int ItemID { get; set; }
        public string ItemTitle { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public string ItemPic { get; set; }
        public string CategoryTitleAr { get; set; }
        public string CategoryTitleEn { get; set; }
        public int CategoryID { get; set; }
        public string GroupTitleAr { get; set; }
        public string GroupTitleEn { get; set; }
        public Nullable<int> Sort { get; set; }
        public string GroupPic { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ItemSizeTitle { get; set; }
        public string ItemColorTitle { get; set; }
        public string ColorCode { get; set; }
        public int GroupId { get; set; }
    }
}
