//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Item
    {
        public int ItemID { get; set; }
        public int CategoryID { get; set; }
        public string ItemTitle { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public string ItemPic { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<double> Points { get; set; }
        public Nullable<double> PointsCredit { get; set; }
        public Nullable<int> NoOfViews { get; set; }
        public string CategoryTitleAr { get; set; }
        public string CategoryTitleEn { get; set; }
        public string SubCategoryTitleAr { get; set; }
        public string SubCategoryTitleEn { get; set; }
        public string ItemColorTitle { get; set; }
        public string ItemSizeTitle { get; set; }
        public string SupplierTitle { get; set; }
        public string SupplierMobile { get; set; }
    }
}
