//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OldOrders
    {
        public int ItemID { get; set; }
        public int CategoryID { get; set; }
        public string ItemTitle { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public string ItemPic { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<double> Points { get; set; }
        public Nullable<double> PointsCredit { get; set; }
        public Nullable<int> NoOfViews { get; set; }
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> DeliveryFees { get; set; }
        public Nullable<double> Net { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> CustomerAddressID { get; set; }
        public Nullable<double> UsedPoints { get; set; }
        public Nullable<double> UsedPointsCredit { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<int> ItemColorID { get; set; }
        public Nullable<int> ItemSizeID { get; set; }
    }
}
