//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPointAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ShoppingCart
    {
        public int ShoppingCartItemID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public Nullable<double> ItemTotal { get; set; }
        public Nullable<int> ItemColorID { get; set; }
        public Nullable<int> ItemSizeID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string ItemTitle { get; set; }
        public string ItemPic { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public string ItemDescription { get; set; }
        public string ItemSizeTitle { get; set; }
        public string ItemColorTitle { get; set; }
        public Nullable<double> PointsCredit { get; set; }
        public Nullable<double> Points { get; set; }
    }
}
